# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f61ba9db6a9041e7244b90fbf5dcff37e6c4f263fe16bf58f6776d3f9d70a0c81bdccac6f0983cfacf31456d5c0cca101308fd877cd55d858d13f7d4c084734d

test:
  secret_key_base: 026fea1b1961bedc5f6b2ad95f090c0b58528074c1fc05a56844e990cd8fa91c5ce500bc419882873ecc58a73935cde1b673ec5b99d5ab3b79868be3f50ef33c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
